https://www.programasaudefacil.com.br/calculadora-de-imc

IMC = PESO / (ALTERA * ALTURA)

FAIXA IMC              CLASSIFICAÇAO  OBESIDADE (GRAU)              
MENOR QUE 18,5   	MAGREZA 	0
ENTRE 18,5 E 24,9	NORMAL  	0
ENTRE 25,0 E 29,9	SOBREPESO	I
ENTRE 30,0 E 39,9	OBESIDADE	II
MAIOR QUE 40,0		GRAVE   	III